### ISSUE TITLE
Another way to combine the m4v and m4a files with ffmpeg

### ISSUE THREAD

**Issue by ftitreefly** [Tusko/vimeo-private-downloader#1]
Another way to combine the m4v and m4a files with ffmpeg

`ffmpg -i video.m4a -i video.m4v -c copy video.mp4`

**Comment by Tusko** [comment]
Added example bash script in https://github.com/Tusko/vimeo-private-downloader/commit/69bc41df8bf072e34cc46504c75dcf8b6f65957e that converts multiple parts
