### ISSUE TITLE
Error while running vimeomaster.js

### ISSUE THREAD

**Issue by noto10** [Tusko/vimeo-private-downloader#12]
Hi, I have node.js installed but encountered the following error while running node vimeomaster.js

```

c:\node\node-v12.18.1-win-x86>node vimeomaster.js
undefined:1
<HTML><HEAD>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (c:\node\node-v12.18.1-win-x86\node vimeomaster.js:123:41)
[90m    at IncomingMessage.emit (events.js:327:22)[39m
[90m    at endReadableNT (_stream_readable.js:1221:12)[39m
[90m    at processTicksAndRejections (internal/process/task_queues.js:84:21)[39m
```

**Comment by Tusko** [comment]
hi @noto10 ,
can you share an url of json file?

**Comment by Nirvanatin** [comment]
@Tusko I have the same problem. The url is:
https://136vod-adaptive.akamaized.net/exp=1599253487~acl=%2F319654135%2F%2A~hmac=b89e9bfae6377c7b0c7f9c6e96f2a4a74e1251ac1aea1419cb522d530056c592/319654135/sep/video/1239708369,1239708359,1239708358,1239708356/master.json?base64_init=1

`undefined:1
<HTML><HEAD>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\Users\JJ\Downloads\vimeo-private-downloader-master\vimeo-private-downloader-master\vimeomaster.js:130:41)
[90m    at IncomingMessage.emit (events.js:326:22)[39m
[90m    at endReadableNT (_stream_readable.js:1244:12)[39m
[90m    at processTicksAndRejections (internal/process/task_queues.js:80:21)[39m
`
