### ISSUE TITLE
Incompleted downloads are skipped if restart is needed

### ISSUE THREAD

**Issue by linomassarani** [Tusko/vimeo-private-downloader#14]
If occurs an error while you are downloading you'll need to stop the app in some cases.

Then, when you restart it, it considers that you already downloaded the incompleted file and just skip it. Then when you use the 'vimeo-combine' tool, the final video can be either with incomplete audio or video.

**Comment by linomassarani** [comment]
@Tusko Are you still accepting pull requests? If so, I can give the repo this feature, let me know and thanks for your code!

**Comment by Tusko** [comment]
merged! thanks
