### ISSUE TITLE
Multithreading  File Downloading

### ISSUE THREAD

**Issue by yusufmsalh** [Tusko/vimeo-private-downloader#19]
the download process usually starts with video files then audio files ,is it possible to use some threading to download both the files to save waiting time.

**Comment by Wesitos** [comment]
Multithreading (or real parallelism) is not needed. A file download is an action that is mostly IO bound, so in JS we use non-blocking calls to achieve concurrency. In the script, the segments of a file are downloaded sequentially and written to disk as soon as possible. Is a very memory efficient way of downloading a file. Also both audio and video files are downloaded (for any special reason, i think)

You can download both files at the same time (the console progress output wouldn't look pretty in that case) or you can download multiple segments at the same time (this may be a little more network-efficient). This can be kind of messy using callbacks. I refactored the code to use async functions (for better readability) and an async generator to manage concurrent segment downloads.

Check it up if you are interested
https://gist.github.com/Wesitos/dde21184b8eff3e9004ba8cd4b5c3c8a

**Comment by Tusko** [comment]
@Wesitos can you provide the PR?

**Comment by Tusko** [comment]
Closed due to inactivity
