### ISSUE TITLE
downloaded video can not play and throw error on console 

### ISSUE THREAD

**Issue by hkvincent** [Tusko/vimeo-private-downloader#23]
with the latest version, the downloaded video can not be played successfully and throw the blew error.
can you help to fix it, thank you very much?

my node version is 13.14.0

fs.js:1061
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink 'C:\Users\Administrator\Desktop\temporary\vimeo-private-downloader-master\parts\.Beluga test.m4a~'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at combineSegments (C:\Users\Administrator.ZGC-20130905TJJ\Desktop\temporary\vimeo-private-downloader-master\index.js:98:8)
    at IncomingMessage.res.on (C:\Users\Administrator.ZGC-20130905TJJ\Desktop\temporary\vimeo-private-downloader-master\index.js:114:9)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by Tusko** [comment]
Please clean parts and converted folders before script running

**Comment by hkvincent** [comment]
still thrown the error

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
[90m    at WriteStream.Writable.write (_stream_writable.js:286:11)[39m
    at IncomingMessage.<anonymous> (C:\Users\Administrator.ZGC-20130905TJJ\Desktop\temporary\vimeo-private-downloader-master\index.js:111:34)
[90m    at IncomingMessage.emit (events.js:315:20)[39m
[90m    at addChunk (_stream_readable.js:297:12)[39m
[90m    at readableAddChunk (_stream_readable.js:273:9)[39m
[90m    at IncomingMessage.Readable.push (_stream_readable.js:214:10)[39m
[90m    at HTTPParser.parserOnBody (_http_common.js:130:24)[39m
    at HTTPParser.execute (<anonymous>)
[90m    at TLSSocket.socketOnData (_http_client.js:472:22)[39m
[90m    at TLSSocket.emit (events.js:315:20)[39m
Emitted 'error' event on WriteStream instance at:
[90m    at emitErrorNT (internal/streams/destroy.js:84:8)[39m
[90m    at processTicksAndRejections (internal/process/task_queues.js:84:21)[39m {
  code: [32m'ERR_STREAM_WRITE_AFTER_END'[39m
}

**Comment by Tusko** [comment]
Mayse something with permissions?
Did you try to run script with sudo?

**Comment by Tusko** [comment]
Oh
It's Windows.
I have not been working with windows few years.
Just MacOS

**Comment by hkvincent** [comment]
But I switch to linux[ubuntun[ still has this issue.
has cleaned up the folder.
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, unlink './parts/.Beluga test.m4a~'
    at Object.unlinkSync (fs.js:949:3)
    at combineSegments (/home/vincent/Desktop/Untitled Folder/vimeo-private-downloader-master/index.js:98:8)
    at IncomingMessage.res.on (/home/vincent/Desktop/Untitled Folder/vimeo-private-downloader-master/index.js:114:9)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
vincent@ubuntu:~/Desktop/Untitled Folder/vimeo-private-downloader-master$

**Comment by NathanielBenguira** [comment]
Hello guys!

Same error for me.
On Mac OS Big Sur
Node version v14.15.1



[...]
→ 📦 🎧 Downloading audio segment 72/72 of ./parts/Introduction.m4a
→ ⚠️  Error: connect ECONNREFUSED 127.0.0.1:443
internal/fs/utils.js:308
    throw err;
    ^

Error: ENOENT: no such file or directory, unlink './parts/.Introduction.m4a~'
    at Object.unlinkSync (fs.js:1210:3)
    at combineSegments (/Users/XXXXXXXXX/Downloads/vimeo-private-downloader-master/index.js:98:8)
    at IncomingMessage.<anonymous> (/Users/XXXXXXXXX/Downloads/vimeo-private-downloader-master/index.js:114:9)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  syscall: 'unlink',
  code: 'ENOENT',
  path: './parts/.Introduction.m4a~'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vimeodownload@1.0.0 start: `node ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vimeodownload@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/XXXXXXXXX/.npm/_logs/2021-02-07T10_45_44_059Z-debug.log

**Comment by andreaemonti** [comment]
Same error, on Linux. Commented the line giving the error 
`//fs.unlinkSync(downloadingFlag);`
now the script do not crash and simply does not remove the 0B temporary hidden files (with name ending with ~), but still after downloaded all video segments for a file, says some errors, begin to redownload only audio segments, but the results is a full video (with no audio) and an audio file (of >100MB) which plays the first 3 seconds of audio and then stops.

With the next video instead I'm stuck in a loop:

```
⚠️  TITLE.m4a - audio is incomplete, restarting the download
→ 📦 🎧 Downloading audio segment 0/504 of ./parts/TITLE.m4a
→ 📦 📹 Downloading video segment 504/504 of ./parts/TITLE.m4v
→ 📦 🎧 Downloading audio segment 328/504 of ./parts/TITLE.m4a
→ ⚠️  Error: connect ECONNREFUSED 127.0.0.1:443
→ ⚠️  TITLE.m4a - audio is incomplete, restarting the download
→ 📦 🎧 Downloading audio segment 0/504 of ./parts/TITLE.m4a
→ 📦 🎧 Downloading audio segment 239/504 of ./parts/TITLE.m4a
→ 📦 📹 Downloading video segment 448/504 of ./parts/TITLE.m4v
...
```

**Comment by leoshusar** [comment]
Same error for me, any progress or workaround?

**Comment by andreaemonti** [comment]
No, but I found this alternative
https://github.com/eMBee/vimeo-download
In python, and uses ffmpeg. It worked for me

**Comment by amonsosanz** [comment]
I've also experienced the problem `Error: connect ECONNREFUSED 127.0.0.1:443`.

I think that the bug that produces this problem is in the function `combineSegments`.

When it's checked whether the last segment has been processed:

```javascript
if (i >= segmentsUrl.length) {
  fs.unlinkSync(downloadingFlag);
  log("🏁", ` ${filename} - ${type} done`);
  cb();
}
```
The callback `cb()` is called, but there's no `return`, so the "non existing segment" is processed anyway. This produces `segmentsUrl[i]` to evaluate as `undefined` producing the error in the request.

Adding the return fixed the issue for me:

```diff
diff --git a/index.js b/index.js
index 8cb6021..67117c7 100644
--- a/index.js
+++ b/index.js
@@ -98,6 +98,7 @@ function combineSegments(type, i, segmentsUrl, output, filename, downloadingFlag
     fs.unlinkSync(downloadingFlag);
     log("🏁", ` ${filename} - ${type} done`);
     cb();
+    return;
   }
```

I suspect that some of the other problems described here may be related to this.

Thanks for this great script!

**Comment by Tusko** [comment]
@amonsosanz 
Hi, you can always create a pull request. Thanks

**Comment by amonsosanz** [comment]
> @amonsosanz
> Hi, you can always create a pull request. Thanks

I will next time!

**Comment by Tusko** [comment]
@amonsosanz  I've already fixed it. thanks
