### ISSUE TITLE
Only works with some videos

### ISSUE THREAD

**Issue by ninze** [Tusko/vimeo-private-downloader#24]
From my experience the script works for some videos and doesn't work for others.

Looking at `master.json` file of failed videos, I noticed that all of them have `base_url='../../../'`, while the successful videos had `base_url='../'`. This is just an observation, not sure if it is actually causing the error.

Failed videos seem to be downloading fine, however they can't be previewed nor combined using the combine tool. Ffmpeg complains about not being able to find the moov atom during the combine process.

I wanted to paste the contents of `master.json` but it is rather large and is not accepted in pastebin.

**Comment by keponk** [comment]
same issue. there seems to be another layer of around some videos. 

EDIT: adding more info. Looking further into the `ffmpeg` error I saw someone suggest the data may be encrypted. I coincidentally noticed this on my console while streaming the video in question
```
Adaptive Video Streaming Service by www.bitmovin.com instrument.js:110:45
Player Version 8.55.0 instrument.js:110:45
EmeEncryptionSchemePolyfill: No native encryptionScheme support found. Patching encryptionScheme support. instrument.js:110:45
```
 Some forums related to encrypted video in general suggested a key might be available to decrypt but this is where i hit a wall with my knowledge. Could there be a decription key somewhere we could use? or is this a blocker related to DRM stuff?

**Comment by keponk** [comment]
@ninze this solution and explanation worked for me: https://gist.github.com/mistic100/895f6d17b1e193334882a4c37d0d7748#gistcomment-3579182 
this is another fork of the parent script this project was based on (I believe)
