### ISSUE TITLE
node index.js throws an error

### ISSUE THREAD

**Issue by cay7man** [Tusko/vimeo-private-downloader#42]
→ ⚠️  The master.json file is expired or crushed. Please update or remove it from the sequence (broken on 0 position)

Any ideas why?

**Comment by Tusko** [comment]
Hi @cay7man!
Yes, master.json has an expiration date.

For example https://2vod-adaptive.akamaized.net/exp=1675166763~acl=%2F914582af-f371-4e77-82ea-dca138cd67b9%2F%2A~hmac=fe7e324dc27c231dbc4f970fb1d471917f85727901fe555118fd27ad5d475979/914582af-f371-4e77-82ea-dca138cd67b9/sep/video/f4fc9f0f,3ad43d2a/master.json?base64_init=1

The parameter `exp` is expiration.
You can check expiration here, but `exp * 1000`
https://currentmillis.com/?1675166763000
