### ISSUE TITLE
Problem with combine

### ISSUE THREAD

**Issue by GerardSD19** [Tusko/vimeo-private-downloader#44]
I can't combine the parts in windows

**Comment by ghost** [comment]
> I can't combine the parts in windows

What is the error you get? You need ffmpeg installed for the combine to work. You can download from 

https://www.gyan.dev/ffmpeg/builds/#release-builds or
https://github.com/BtbN/FFmpeg-Builds/releases

extract it and ensure that the directory is in the path. In powershell you can check with `Get-Command ffmpeg` then.

**Comment by postlemons** [comment]
As @jhorchler mentioned in his reply, **ffmpeg** is needed _(search up "how to install it" if you don' have it)_.
If you have it installed 'n end up with ```'sh' is not recognized as an internal or external command```; that's 'cause you're tryna use Linux commands on windows. 
You can use [Git](https://git-scm.com/) as a solution for that, but you need to add it to System Path Environment Variables.

---
### How to add it to System Environment Variables?
you can do that by searching "system variables" in your windows search or opening the properties of "this pc" on your desktop, then follow these steps:

Select ```Advanced``` Tab > Press ```Environment Variables...``` > Select ```Path``` > Press ```Edit``` > Press ```New``` > Enter your Git installation directory path + "\bin" _(Example: ```C:\Program Files\Git\bin```)_ > Press ```Ok```
that's it, you can test if it works or not by opening up your CMD 'n typing ```sh```, if you get the same error, try in administrator mode. _(works only in administrator mode? start VS Code in administrator mode whenever you need the script)_
Hope this fixes your issue.

**Comment by riclombardi** [comment]
Hi,

I also had some problems to get the powershell script to work, and I wanted to share my experience.

If you get an error like this:

`ForEach-Object : Parameter set cannot be resolved using the specified named parameters.`
`[...]`
`FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.PowerShell.Commands.ForEachObjectCommand`

You need to upgrade to Powershell 7X. `ForEach-Object -Parallel` has been introduced in PowerShell 7.0. Any version above will work.

Hope it helps.
