### ISSUE TITLE
Error: connect ETIMEDOUT 2001:4450:3a::ca8a:b370:443

### ISSUE THREAD

**Issue by Unorthodoxis-ui** [Tusko/vimeo-private-downloader#47]
Getting this error:
Video to be downloaded is uploaded in a private vimeo account, not sure if its encrypted, but it is embedded in a portal site.

Error: connect ETIMEDOUT 2001:4450:3a::ca8a:b370:443

Appears when:
1. Master.json - has base64_init=1&query_string_ranges=1

1. Tried removing &query_string_ranges=1, still occurs
2. Tried removing ?base64_init=1, still occurs

**Comment by Tusko** [comment]
Hey
Looks like you video link is expired

**Comment by Unorthodoxis-ui** [comment]
I guessed as much, found out an alternative through a 3rd party site.

Question, I am having a problem with downloading a video (~5 hours long) seems like the video only downloads up to the 32 min mark (approximately 1GB m4v data) while the audio downloads completely. Is there a workaround for this?

**Comment by Unorthodoxis-ui** [comment]
My bad, turns out I accidentally closed the terminal before the combining finished. Consider this closed and resolved. Thank you.
