### ISSUE TITLE
error with characters from the titles of the list of "master.json"

### ISSUE THREAD

**Issue by GustavoNovaisR** [Tusko/vimeo-private-downloader#5]
sorry i'm learning i'm still learning to program and i still don't know how github works (unfortunately).

but I found a problem with characters in the titles of the lists.

when using ["\], [?], ['] and ["] errors occur when saving the files in the "fs" (file System) and also with the executable "combine.sh"

**Comment by Tusko** [comment]
I don't see problem with special characters, but thank you for the message.
I've fixed the paths in https://github.com/Tusko/vimeo-private-downloader/commit/be851ef9bcede6c74ac8c559b8a29d820f9e282a,  now it works fine.
