### ISSUE TITLE
Feature request: Make a simple GUI

### ISSUE THREAD

**Issue by renatobellotti** [Tusko/vimeo-private-downloader#51]
Hi,

Thank you so much for this excellent tool! It has earned me some impressed remarks regarding "computer magic". I am aware that making the tool more user friendly might cause legal consequences. However, I believe that your software could be even more awesome by providing the full user-friendliness. I envision a simple GUI where the user only has to provide a URL or even a list of URLs. Then, the code opens the webpage (e. g. using [Selenium](https://www.npmjs.com/package/selenium-webdriver)), looks for the ``master.js`` file, writes the ``videojson.js`` file and then calls the existing code.

I'm looking forward to hearing your thoughts about my suggestion.

Cheers!

**Comment by Tusko** [comment]
@renatobellotti feel free to create Pull Request
