### ISSUE TITLE
Audio/Video Cutoff

### ISSUE THREAD

**Issue by paste2k** [Tusko/vimeo-private-downloader#6]
Your script is great! Thank you so much! 
But I found one issue:
If I fill my videojson.js with a lot of master.json urls, which belong to huge videos, the audio and video source files are being downloaded corruptly. 
Is there a way to download the files sequentially?

**Comment by Tusko** [comment]
I've created a modified script with sequential downloads in new branch  [🌱 feature/sequential-download](https://github.com/Tusko/vimeo-private-downloader/tree/feature/sequential-download)

Please test it and let me know. then I'll create PR to master

**Comment by paste2k** [comment]
I tested it yesterday and it works like a charm. No more corrupt files :)
Thanks a lot, I really appreciate your work!
