### ISSUE TITLE
Error when launching the script

### ISSUE THREAD

**Issue by sylvain640** [Tusko/vimeo-private-downloader#9]
Hello and thank you for this very good work!

But I've got errors launching this script : 

![screenshot](https://user-images.githubusercontent.com/64095470/79893628-a15a3280-8404-11ea-8f41-ee83befd19f6.png)

Do you think you can help me? 
Thank you very much from France!
Sylvain

**Comment by Tusko** [comment]
@sylvain640 hello.
Can you check folders permissions?

**Comment by Tusko** [comment]
Or try to launch with `sudo`
@sylvain640

**Comment by sylvain640** [comment]
@Tusko 
Thank you for your quick reply!
I'm admin and I've all permissions on folders...

**Comment by Tusko** [comment]
that's strange.
Try to clean up /parts/ folder

**Comment by sylvain640** [comment]
@Tusko 
I've been too rushed!
It's now ok with su rights!

Thank you for this work!
